### ISSUE TITLE
[mig future] implement http/2 in API and clients (Bugzilla #1104992)

### ISSUE THREAD

**Issue by jvehent** [mozilla/mig#105]
Migrated from https://bugzilla.mozilla.org/show_bug.cgi?id=1104992
Assigned to: Julien Vehent [:ulfr]

On 2014-11-25 13:45:23 -0800, Julien Vehent [:ulfr] wrote:

> https://github.com/bradfitz/http2/ provides support for HTTP2 in Go. Considering the large number of API requests between a client and the MIG API, HTTP/2 could provide a significant speedup. It would also provide a cleaner alternative to websocket, to allow the API to push action status updates without requiring requests from the client.

**Comment by vbmade2000** [comment]
@jvehent  http2 is enabled by default in Go 1.6+ with no changes to your code. Is it still required to implement http2 in mig ?

**Comment by jvehent** [comment]
This can be closed.
