### ISSUE TITLE
[mig scheduler] output logs in json format, publish to mozdef (Bugzilla #1109877)

### ISSUE THREAD

**Issue by jvehent** [mozilla/mig#106]
Migrated from https://bugzilla.mozilla.org/show_bug.cgi?id=1109877
Assigned to: Julien Vehent [:ulfr]

On 2014-12-10 13:54:06 -0800, Julien Vehent [:ulfr] wrote:

> The MIG scheduler should be able to output logs into MozDef's AMQP endpoint in a proper JSON format.

**Comment by ameihm0912** [comment]
Equivalent functionality was added in https://github.com/mozilla/mig-deploy/pull/2
