### ISSUE TITLE
[mig agent] Windows support & MSI packaging (Bugzilla #1116003)

### ISSUE THREAD

**Issue by jvehent** [mozilla/mig#107]
Migrated from https://bugzilla.mozilla.org/show_bug.cgi?id=1116003
Assigned to: Julien Vehent [:ulfr]

On 2014-12-28 10:43:22 -0800, Julien Vehent [:ulfr] wrote:

> Running mig-agent on windows currently works in foreground, with options "-f" or "-d". From today's tests, it seems that the mig-agent service is not properly installed and configured, which prevents it from running in background. This may be an issue with the service-go package.
> 
> MSI packaging mostly works, but two things need to be added to the WXS file:
> - shortcut creation to link C:\Program Files\mig\mig-agent-<VERSION>.exe to C:\Program Files\mig\mig-agent.exe
> - command execution at the end of the MSI install to run mig-agent
> 
> Today's work is committed in https://github.com/mozilla/mig/commit/SHA: e6ed8a490d60cc38367df1c9d4803356bf7adc28 . To be continued...

**Comment by mvanotti** [comment]
Hi!
I was able to create the shortcut without problems, but I need a little bit more information about the WXS file (https://github.com/mozilla/mig/blob/master/conf/mig-agent-installer.wxs )

The guids are created randomly? Should I just create a new guid for any new element I'd like to add?
Why does the MainExecutable have a GUID as its id? Is it inteded to be the same forever? We could use something like MigAgentBinary as the id.

**Comment by jvehent** [comment]
I have limited understanding of WXS, but I think at least the `product.Id` and `ProductUpgradeCode` need to remain the same across releases. The rest can probably change.
But if you've got a better way to do this, feel free to change it.

**Comment by mvanotti** [comment]
I see that. But I'm talking about the Id of the File in the MainExecutable component, I need to refer to that from the ShortCut. It's ok, I can reuse that Id, but all the tutorials and examples I've seen use more detailed names, in this case, something like migAgentExe or migAgentBinary

**Comment by jvehent** [comment]
This one?
```xml
<File Name='mig-agent-$(var.ProductVersion).exe'
    Id='25ac5e4f-3f70-4e21-9389-7e5fcd6fde9d' />
```
If it's just a string and doesn't need to conform to a uuid format, just replace it with something sensible. `MigAgentBinary` sounds good.

**Comment by ameihm0912** [comment]
Issue no longer relevant as a number of Windows related changes have been made since
