### ISSUE TITLE
[mig client] Add option for target agents from results of previous action (Bugzilla #1141910)

### ISSUE THREAD

**Issue by jvehent** [mozilla/mig#115]
Migrated from https://bugzilla.mozilla.org/show_bug.cgi?id=1141910
Assigned to: Julien Vehent [:ulfr]

On 2015-03-10 20:56:03 -0700, Julien Vehent [:ulfr] wrote:

> Add options that automatically implements http://mig.mozilla.org/doc/cheatsheet.rst.html#target-agents-that-found-results-in-a-previous-action
> 
> mig file -t "id IN ( \
>     SELECT agentid FROM commands, json_array_elements(commands.results) AS r \
>     WHERE commands.actionid = 12345 AND r#>>'{foundanything}' = 'true')" \
> -path /etc/passwd -content "^spongebob"
> 
> For example:
> * --target-foundanything <actionid> would limit the targets to agents that returned positive results in <actionid>
> * --target-foundnothing <actionid> would do the opposite and target agents that did not return positive results in <actionid>
> 
> This option should concatenate with the regular -t option such that an investigator could set both and filter the results even further.

On 2015-03-10 20:56:41 -0700, Julien Vehent [:ulfr] wrote:

> Implementation should take the form of two new options in the command line client at https://github.com/mozilla/mig/blob/master/src/mig/client/cmd/main.go#L75

**Comment by arunk-s** [comment]
Hey, I'm interested to want to work on this feature.
The link you mentioned in the description is obsolete now ;), maybe you meant this one https://github.com/mozilla/mig/blob/master/client/mig/main.go .
From what I understand is we need to add two flags: `--target-foundanything` and `--target-foundnothing` and they should be evaluated by [`EvaluateAgentTarget`](https://github.com/mozilla/mig/blob/master/client/client.go#L725). Does the flags `--target-found*` hold "Action ID" as their values, so we build this query 
```
id IN ( \
SELECT agentid FROM commands, json_array_elements(commands.results) AS r \
WHERE commands.actionid = %d AND r#>>'{foundanything}' = 'true')" )
````
from the passed value and pass it for evaluation ?
Also what preference is given to `-t` flag in case of use of both `-t` and `--target-found*` flags, i.e. should the agents that passes the `-t` flag should be filtered further on the basis of the `-target-found*` flags or vice versa ?

**Comment by jvehent** [comment]
Thanks for picking up this issue :)

> maybe you meant this one https://github.com/mozilla/mig/blob/master/client/mig/main.go .

Yes

> does the flags --target-found* hold "Action ID" as their values

Yes

> what preference is given to -t flag in case of use of both -t and --target-found* flags

For now, execution should fail and an error should be displayed to the user.
In the future, we could considered merging the two statements together.

**Comment by arunk-s** [comment]
@jvehent PR created and the updated code is at https://github.com/arunk-s/mig/commit/c94ef413933bfca760e857bc6d4d3c1a316834fd.
