### ISSUE TITLE
[mig modules] timedrift should read target ntp server from /etc/ntp.conf (Bugzilla #1149496)

### ISSUE THREAD

**Issue by jvehent** [mozilla/mig#116]
Migrated from https://bugzilla.mozilla.org/show_bug.cgi?id=1149496
Assigned to: Julien Vehent [:ulfr]

On 2015-03-31 05:45:42 -0700, Julien Vehent [:ulfr] wrote:

> In some instances, endpoints cannot establish NTP connections with pools from the internet. Timedrift should attempt to connect to locally configured NTP servers first, by reading /etc/ntp.conf and parsing the ^server entries, and then use internet servers if no local ones are available.

**Comment by eXeC64** [comment]
@jvehent Mind if I take a crack at this?

**Comment by jvehent** [comment]
Please do! I'm happy to help too, don't hesitate to reach out :)
