### ISSUE TITLE
[mig loader] loader should use packages (Bugzilla #1151660)

### ISSUE THREAD

**Issue by jvehent** [mozilla/mig#118]
Migrated from https://bugzilla.mozilla.org/show_bug.cgi?id=1151660
Assigned to: Julien Vehent [:ulfr]

On 2015-04-06 15:56:34 -0700, Julien Vehent [:ulfr] wrote:

> Instead of pushing a binary, the upgrade module should use a rpm/deb/dmg/wmi package to install new versions of the agent.

**Comment by jvehent** [comment]
We're replacing the upgrade module with a loader, so rephrasing this issue.

**Comment by vbmade2000** [comment]
@jvehent Can this issue be closed ?
