### ISSUE TITLE
mig unable to find gpg key to create configuration file

### ISSUE THREAD

**Issue by gene1wood** [mozilla/mig#132]
I'm not sure the method mig uses to find the gpg key but it might be extended to read the gpg conf file and use the key location indicated in the conf.

It also might be good to improve the error message to clarify that "no suitable key found" means something like

"Unable to find GPG key after searching in these places. To manually set your gpg key do this"

```
mig file --path /home -path /root -name "^authorized_keys" -content "foo"
no configuration file found at /home/jdoe/.migrc
would you like to generate a new configuration file at /home/jdoe/.migrc? Y/n> y
ReadConfiguration() -> MakeConfiguration() -> no suitable key found
```

**Comment by jvehent** [comment]
Have you tried editing the location of the gpg home in ~/.migrc to resolve the issue?
Agreed on the error message: it should be improved.

**Comment by ameihm0912** [comment]
Looks like a fix for this issue was merged a while ago, closing this
