### ISSUE TITLE
[mig modules] mig file hash function selection could be friendlier

### ISSUE THREAD

**Issue by marumari** [mozilla/mig#155]
Instead of requiring:

-sha256 <hash>
-sha384 <hash>
-sha512 <hash>
-sha3_224 <hash>
-sha3_256 <hash>
-sha3_384 <hash>
-sha3_512 <hash>

It should just use:
-sha2 <hash>
-sha3 <hash>

And then look at the hash size (256 bits, 512 bits, etc.) to see what hash function to run.

**Comment by jvehent** [comment]
Seems like a good idea, and a perfect first bug! It should be implemented in this file: https://github.com/mozilla/mig/blob/master/modules/file/paramscreator.go in both the `ParamsCreator` (for the console) and `ParamsParser` (for the cmdline) functions.
