### ISSUE TITLE
unable to install on OSX El Captain after building a dmg-agent

### ISSUE THREAD

**Issue by zhenyuzhong** [mozilla/mig#188]
Hi,

I tried to deploy agent on Mac OS. 
I installed GO1.6 on my Mac OS El Captain. I also have fpm installed through gem. 
I fixed the libc.dylib could not open issue by referencing ffi_lib to '/usr/lib/libc.dylib' rather than FFI::Library:LIBC
After all these, I was able to pull off a build on dmg-agent. 

However, when I tried to install that it complained about imcompatible package.

Any thoughts?

Many thanks!
edward

**Comment by ameihm0912** [comment]
Believe this may be related to it attempting to install to /sbin/, which isn't permitted with el capitan.

I've run into this recently (changed in my branch in 30be57f). It looks like we need to fix this in this install target as well.

**Comment by zhenyuzhong** [comment]
Hi Aaron,

I tried to follow your branch in 30be57f, also made changes to the install
path.(change from /sbin/ to /usr/local/bin) After building with the
following command
make dmg-agent OS=darwin AGTCONF=myconf.conf,  I got the dmg file.
However, during the installation, it still complained about "incompatible".

In your previous comment, it seems there is one more edit to make which is
the install target. Where is it?

Please kindly advise.

best,
edward

**Comment by zhenyuzhong** [comment]
Looks like making changes to the manifest.go file doesn't help. The dmg
file still tries to install to /sbin.
I also tried to make changes to the Makefile so that agent-install-script
and agent-remove-script so that it points to /usr/local/bin.

With these changes, the dmg being built still tries to install to /sbin

Please kindly let us know where in the source code we can make changes so
that it won't install to /sbin?

thanks
edward

**Comment by ameihm0912** [comment]
Hi, can you try updating to the latest in that branch de2a6d8 and see if this helps?

This branch is tracking some of our work around agent auto-updates; I hadn't changed the dmg package install as part of that, but just did now. Let me know if it works.

**Comment by zhenyuzhong** [comment]
Hi Aaron,

The branch de2a6d8 does work. I was able to build and run the agent.

thanks
edward

**Comment by ameihm0912** [comment]
This is in master now as 54ce65e, closing this off
