### ISSUE TITLE
mig-agent does not start properly on archlinux (installed via mig-loader): overrides all settings, and fails to start anyway

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/mig#200]
> Mar 24 14:12:56 xps13 systemd[1]: Started Mozilla InvestiGator Agent.
> Mar 24 14:12:56 xps13 mig-agent[19884]: [info] Using external conf from "/etc/mig/mig-agent.cfg"
> Mar 24 14:12:57 xps13 systemd[1]: mig-agent.service: Main process exited, code=exited, status=1/FAILURE
> Mar 24 14:12:57 xps13 systemd[1]: mig-agent.service: Unit entered failed state.
> Mar 24 14:12:57 xps13 systemd[1]: mig-agent.service: Failed with result 'exit-code'

starting mig-agent with 'mig-agent -d' works fine.
starting mig-agent by hand without '-d' attempts to restart from the systemd file (and forces re-enabling the service and overwrites the service file, which is unexpected after user disable it or changes the service file). This is IMO unacceptable for user experience on laptops.
This also means I cannot test fixing the systemd service file (mig-agent always detect the changes overwrite them and self restart) without recompiling my own mig agent ;-)

**Comment by gdestuynder** [comment]
Additionally the service file repeats the same unit arguments (start limit interval/burst), the 2nd will override the first:

`[Unit]
Description=Mozilla InvestiGator Agent
ConditionFileIsExecutable=/usr/bin/mig-agent

[Service]
StartLimitInterval=5
StartLimitBurst=10
ExecStart=/usr/bin/mig-agent

# respawn process on crash after a 3s wait
# if fails to start 5 times within 5 minutes, stop trying
Restart=on-failure
RestartSec=3s
StartLimitInterval=300
StartLimitBurst=5

[Install]
WantedBy=multi-user.target
`

**Comment by ameihm0912** [comment]
In my testing the failure appears to be occuring in installCron(); arch doesn't normally have cron running by default (or /etc/cron.d) so it's likely something in there causing the problem.
