### ISSUE TITLE
Implement loader log output

### ISSUE THREAD

**Issue by ameihm0912** [mozilla/mig#204]
mig-loader should log runs to a log file for review, currently logging happens via stdout. Change this to a generalized logging routine that writes to a file so we do not need to redirect the output in various ways depending on the platform its running on.

**Comment by jvehent** [comment]
Why not use the standard logging functions the api, scheduler and agent use?

**Comment by ameihm0912** [comment]
Yeah I think so, what we may need to look at is adding some sort of basic rotation for the file output mode, since we can't expect users to truncate log files on a workstation

**Comment by jvehent** [comment]
That shouldn't be too hard. Maybe start a goroutine that sleeps for X amount of time when the logger is initialized, resets the `log.SetOutput(fd)` to a new file when wakes up, and closes and moves the old file.
