### ISSUE TITLE
Limit amount of walking errors returned by file module

### ISSUE THREAD

**Issue by jvehent** [mozilla/mig#227]
The `file` module currently all of the walking errors it encounters when processing a path. Sometimes searches on `/` can return so many errors that the relays get overloaded with large amount of data to pass through to the scheduler.

99% of the time, we don't care about walking errors, so rather than returning all of them the file module should return a summary, or a limit of 100.

**Comment by bipuldutta** [comment]
Curious, why the limit of 100?

**Comment by jvehent** [comment]
No particular reason, it just seems like a sensible default. Although, maybe a prime number would be better, what about `107`?.
At any rate, it should be configurable via a flag.
