### ISSUE TITLE
Replace API X-PGP-Authorization with basic tokens

### ISSUE THREAD

**Issue by jvehent** [mozilla/mig#239]
X-PGP-Authorization was a good bad idea. While very secure because the server never sees the private key, it's also non-standard and thus hard to implement in clients that don't directly use the MIG codebase.
The motivation behind X-PGP-Authorization was to avoid managing another set of keys when investigators already had to manage a PGP key to sign actions. However, we now have several client types that do not have PGP keys (loader, runner, some webui dashboard in the future) and requiring x-pgp-authorization just makes things difficult.

A simple API Token (oauth bearer token? jwt? hawk?) would suffice and be more standard.

**Comment by jvehent** [comment]
JWT may be a better fit.

**Comment by jvehent** [comment]
[Stripe](https://stripe.com/docs/api#authentication) uses HTTP Basic Auth on their API, and that doesn't seem like a terrible idea. It's way simpler than any other mechanism, which helps integration. The downside being we need to store API keys server side, when JWT is a pubkey mechanism.

**Comment by ameihm0912** [comment]
We currently have a couple authentication functions being used, authenticate() and authenticateLoader() https://github.com/mozilla/mig/blob/master/mig-api/api.go#L231-L326

One potential option is we adapt the approach used in authenticateLoader to the authenticate function

This would require the addition of properties such as the key prefix/hash to the investigator's entry in the database as well

**Comment by jvehent** [comment]
So we need to rip out `authenticate()` entirely, rename `authenticateLoader()` into `authenticate()` and use it for all endpoints. Then we can create a new DB column in the investigator table where we store the API tokens of clients.

**Comment by ameihm0912** [comment]
Here's one example of how we are currently hashing authorization strings for the loader https://github.com/mozilla/mig/blob/master/mig-api/loaderkey.go

**Comment by jvehent** [comment]
Here's how the loader key and salt are stored in DB: https://github.com/mozilla/mig/blob/master/database/schema.sql#L137-L138
