### ISSUE TITLE
Create an API endpoint for agents to retrieve PGP public keys

### ISSUE THREAD

**Issue by jvehent** [mozilla/mig#240]
Rather than hardcoding long public keys into the agents, we should provide an api endpoint at `/publickey/<pgp_fingerprint>` that returns the armored public key that corresponds to the pgp fingerprint. Agent could then populate their local keyring using data from the API and only have the fingerprints in their local configuration.

**Comment by sunnygkp10** [comment]
what should be format of response ?Is it key only or in json ?

**Comment by ameihm0912** [comment]
@sunnygkp10 I'd say key only is fine here, similar to how we return the public IP: https://github.com/mozilla/mig/blob/master/doc/api.rst#get-api-v1-ip

In most cases the API responses are Collection+JSON but I don't think that would buy us much here, and it would keep it simpler to process if we just return text.

**Comment by jvehent** [comment]
I'm with Aaron: just return the armored public key.

**Comment by sunnygkp10** [comment]
@ameihm0912 All changes are updated 0624393cba02bf9750b136aae6d4f4282e1f903b
