### ISSUE TITLE
Revisit proxy support and order of use

### ISSUE THREAD

**Issue by ameihm0912** [mozilla/mig#249]
Current code we attempt to use configured proxies after a direct connection to the relay fails.

It may be better to try the proxies first if they are configured, and fall back to a direct connection if they fail, or potentially look into a configuration option to use only proxies for connectivity.

**Comment by mpurzynski** [comment]
Trying proxies if configured sounds like a good idea - someone configured them for a reason. The MIG agent should try and fallback to direction connection if proxies are configured but not working (dead or just not passing anything or rejecting with ACLs).
