### ISSUE TITLE
[medium] windows - repository symlinks not compatible

### ISSUE THREAD

**Issue by robmurtha** [mozilla/mig#277]
The following files are symlinks within the repo, when cloning on windows they only contain the path and not the expected contents and are not compilable.

./client/mig/available_modules.go
./client/mig-console/available_modules.go
./mig-agent/available_modules.go
./mig-agent/configuration.go
./vendor/github.com/mozilla/scribe/test/filecontent/data/testfile2

**Comment by jvehent** [comment]
These symlinks are used to facilitate retrieving the binaries with `go get`, but they change rarely, so maybe we can use files instead of links? If so, we should add instruction for travisci to flag out of date files, or they'll get out of date quickly.
