### ISSUE TITLE
Add an option to print agent settings

### ISSUE THREAD

**Issue by ameihm0912** [mozilla/mig#280]
It would be nice to have a way to provide a flag to mig-agent, where it just outputs it's current settings it would run with. This would provide a means to see how the built-in configuration is setup, and how the config file options override the built-in configuration.

Currently there is no easy method to see the configuration of the agent after it has been compiled.

**Comment by vbmade2000** [comment]
@ameihm0912 Can I work on this ?

**Comment by ameihm0912** [comment]
@vbmade2000 absolutely; feel free to grab this one

**Comment by vbmade2000** [comment]
@ameihm0912 Is purpose of client (/client/mig/main.go) communication with mig-agent ?

**Comment by ameihm0912** [comment]
Yes, this that is a command line tool that ultimately communicates with the agents through the API and scheduler. In this case though what we are looking for is just a flag for mig-agent itself to print the settings it is using (e.g., the various compile time built-in configuration settings, and any settings being overridden by a config file).

**Comment by vbmade2000** [comment]
I see. I am going to add that flag in  mig/mig-agent/agent.go. I think that is the right place.

**Comment by vbmade2000** [comment]
@ameihm0912 I have implemented option to print mig-agent settings. Here is the output. It still doesn't print all settings. 
Pls take a look at screenshot of output and let me know the feedback.

![screenshot from 2017-03-18 10-32-57](https://cloud.githubusercontent.com/assets/1904995/24073514/6aa39628-0bc6-11e7-943b-2b0e5571fc20.png)

**Comment by ameihm0912** [comment]
Looks like what we were after -- want to send in a PR for this and I can review ?
