### ISSUE TITLE
windows: netstat - HasListeningPort() is not implemented

### ISSUE THREAD

**Issue by robmurtha** [mozilla/mig#291]
mig netstat -t "environment->>'os' IN ('windows')" -lp 80

**Comment by robmurtha** [comment]
see https://github.com/mozilla/mig/issues/193

**Comment by robmurtha** [comment]
@ameihm0912 @jvehent - netstat is available in windows 10 pro - should I proceed with adding support?

**Comment by ameihm0912** [comment]
Yeah I think so, ideally for each module we has the same functionality on each platform, so it would be good to add this for Windows if we can.

**Comment by robmurtha** [comment]
net.ParseIP does not handle the % in this address [fe80::1c5a:2c75:6ce3:9f0%3]:1900
@jvehent @ameihm0912 what would be an example query to match this? Is it acceptable to just return the IP as a string, if so should it just be the contents within [] ?

**Comment by robmurtha** [comment]
I will just use the parseEndpointString method found in the darwin code.

**Comment by ameihm0912** [comment]
@robmurtha yeah we might need a custom function here, ideally we want results coming back from agents to the same, so for example we don't want a different format IP coming back from Windows vs. other platforms.
