### ISSUE TITLE
Create OSX notifications for agent queries on OSX

### ISSUE THREAD

**Issue by ameihm0912** [mozilla/mig#298]
When an agent receives an action, it might be nice to create a notification (e.g., popup) on OSX indicating the agent is running an action.

**Comment by vbmade2000** [comment]
@ameihm0912  Though I have no background of project I can take this if support is provided.

**Comment by ameihm0912** [comment]
Just closing this; this is a bit more involved due to the agent running as root on OSX. Functionality was recently added to get information on recent actions via the agents status socket, which also covers some of the intent of this issue off.
