### ISSUE TITLE
Do you need an automated code style review tool?

### ISSUE THREAD

**Issue by tgrundmanis** [mozilla/mig#361]
Myself and a cofounder created a style linter developer tool that comments on style errors in GitHub pull requests (for 15 languages and counting, including GO). It is free for open source projects.

You can check out the product on https://stickler-ci.com. Just authorize your GitHub account, enable a public repo, and then open/update an existing pull request (or create a new pull request).

**Comment by jvehent** [comment]
We get spam in github issues now? That's new...
