### ISSUE TITLE
Design a REST API to facilitate action dispatching and documentation retrieval

### ISSUE THREAD

**Issue by zsck** [mozilla/mig#442]
The beginning of the development of our client daemon will start with the design of a REST API that supports the following use cases:

1. [x] Retrieve daemon API documentation
2. [x] Retrieve agent module documentation
3. [x] Create an action, specifying the module to run and any required configuration
4. [x] Dispatch a newly-created action to the MIG API
5. [x] Retrieve information detailing the status of dispatched actions

Before the above can be completed, we will also need to:

1. [x] Specify each module's configuration as a JSON structure
2. [x] Design a JSON structure to describe agents to target

**Comment by vbmade2000** [comment]
@zsck Are you working this ? If not I want to work on this issue.

**Comment by zsck** [comment]
Hey @vbmade2000 I am working on this in the [client-daemon](https://github.com/mozilla/mig/tree/client-daemon) branch. I'd love to welcome your help on this, though!  Would you be willing to have a read through some of the [documentation](https://github.com/mozilla/mig/tree/client-daemon/doc/client) I've put together so far and offer feedback?  I'd really like to make sure that the module configuration types I've specified are accurate and useful. Any improvements would be greatly appreciated!

**Comment by vbmade2000** [comment]
@zsck Ok. I'll surely check documentation and get back to you if I would have any suggestion etc.
