### ISSUE TITLE
[mig api&console] support multiple signatures of actions (Bugzilla #1014742)

### ISSUE THREAD

**Issue by jvehent** [mozilla/mig#98]
Migrated from https://bugzilla.mozilla.org/show_bug.cgi?id=1014742
Assigned to: Julien Vehent [:ulfr]

On 2014-05-22 11:07:41 -0700, Julien Vehent [:ulfr] wrote:

> The client `mig-action-generator` must be able to load an action that has already been signed once, and append another signature to it. This would allow investigators to multi-sign actions that require a higher level of privileges.

On 2014-12-30 19:40:56 -0800, Julien Vehent [:ulfr] wrote:

> This work needs a different strategy: an investigator must be able to sign an action and submit it to the api for more signatures, then launched.
> 
> The API should have a staging area, maybe under /api/v1/action/pending, where action can be registered but not sent. The dashboard resource at /api/v1/dashboard should list action pending signatures.
> 
> The console should list actions pending signatures, allow an investigator to retrieve a pending action, and repost it to the staging area for more signatures, or launch it.

**Comment by ameihm0912** [comment]
Added in da1c176
